---
name: Update biorxiv.org stats
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  updateBiorxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          OUT_DIR: "./data"
          DAYS: ${{ vars.DAYS || '7' }}
          CATEGORIES: ${{ vars.CATEGORIES || '' }}
          SERVER: ${{ vars.SERVER || 'biorxiv' }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
